version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: news_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        ports:
            - "8000:8000"
        depends_on:
            - db
        networks:
            - laravel_network

    db:
        image: mysql:8
        container_name: laravel_db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: news-app
            MYSQL_USER: root
            MYSQL_PASSWORD: rootpassword
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel_network

    nginx:
        image: nginx:alpine
        container_name: laravel_nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel_network

volumes:
    db_data:

networks:
    laravel_network:
        driver: bridge
